### ISSUE TITLE
End of Pilot Program!?!?!

### ISSUE THREAD

**Issue by CmpCtrl** [mjmeli/pydukeenergy#71]
Not really an issue with this tool, but i wanted to comment how bummed i am that this is ending. Argh.

I wonder if there is any way to reconfigure the gateway to get to the data afterwards. I don't understand the system well.

**Comment by brianmaxon** [comment]
I wonder what the possibility would be of using the existing hardware to send entirely local MQTT messages with the energy usage data. If Duke Energy were willing to open access to the hardware, that could be theoretically possible.

**Comment by CmpCtrl** [comment]
I sent an email to the SmartMeterUsageApp@duke-energy.com address asking approximately that. Maybe its worth some more emails to show more interest in it. Surely there's a way to do it, but I'm sure its particularly challenging without some tips from Duke on how to access it.

**Comment by lshep5801** [comment]
And another $0.02..  IIRC earlier in my investigation of the gateway device after I received it, it appears it requires a SSH key to login to the gateway box, and a DNS study showed it talked back to its manufacture across the pond quite frequently.  Two HUGE stumbling blocks to be able to access it without Duke's involvement.

**Comment by CmpCtrl** [comment]
Yea copy that. That would be a bummer.

**Comment by CmpCtrl** [comment]
Not a real encouraging response...

> Thank you for contacting us regarding the Smart Meter Usage App Gateway Device.
> 
> Once the pilot has concluded, you will only be able to see your historical usage at one-hour intervals of any previous date. Most current data is from the previous 24 hours. Your Gateway will no longer connect to your smart meter or send real-time data to the Duke Energy mobile app. To view your daily energy usage data from your smart meter, just [log in](https://www.duke-energy.com/my-account/sign-in) to your Duke Energy account. Watch this video to learn how to access your usage data.
> 
> Best regards,
> Kim C.
> Duke Energy Smart Meter Usage App Team
> 800-366-4703
> [SmartMeterUsageApp@duke-energy.com](mailto:SmartMeterUsageApp@duke-energy.com)

**Comment by mjmeli** [comment]
I'm going to archive this repository since the deprecation went through
